import Head from "next/head";
import Layout from "../components/layout";
import Hero from "../components/Hero";
import Services from "../components/Services";
import { client } from "../lib/client";
import  Menu  from "../components/Menu.jsx";

export default function Home({ pizzas }) {
  console.log(pizzas)
  return (
      <Layout>
      <div>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero /> 
          <Services />
          <Menu pizzas={pizzas}/>
        </main>
      </div>
      </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "Pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas
    }
  }
}